login: &login
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password:

development:
  database: publify_dev
  <<: *login

test:
  database: publify_tests
  <<: *login

production:
  database: publify
  <<: *login